services:

    postgresql:
        container_name: postgresql
        image: postgres:14
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: chats-mats-db
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: {}
